services:
  postgres:
    image: postgres:13
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agent_notebook
    volumes:
      - ./ini_backup.sql:/docker-entrypoint-initdb.d/ini_backup.sql
      - postgres_data:/var/lib/postgresql/data # Ensure defined volume
    ports:
      - "5432:5432"
volumes:
  postgres_data: # Define the volume

# Commands: to start a database
# docker-compose -p postgres up
