services:
  # service backend
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ../backend/.env
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - POSTGRES_URI=postgresql://postgres:postgres@db:5432/agent_notebook
  # service for postgres
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agent_notebook
    volumes:
      # - ./postgres/ini_backup.sql:/docker-entrypoint-initdb.d/ini_backup.sql
      - postgres_data:/var/lib/postgresql/data # Ensure defined volume
    ports:
      - "5432:5432"

volumes:
  postgres_data:
# docker compose -p backend up
