"""remove chunk table and update column name

Revision ID: 709f70c74930
Revises: 8d675daa3dad
Create Date: 2024-11-06 11:21:16.733098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '709f70c74930'
down_revision: Union[str, None] = '8d675daa3dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('note_fk_note_chunk_id_fkey', 'note', type_='foreignkey')
    op.drop_table('chunk')
    op.add_column('file', sa.Column('notebook_id', sa.String(length=100), nullable=False))
    op.drop_constraint('file_fk_file_notebook_id_fkey', 'file', type_='foreignkey')
    op.create_foreign_key('fk_file_notebook_id', 'file', 'notebook', ['notebook_id'], ['notebook_id'], ondelete='CASCADE')
    op.drop_column('file', 'fk_file_notebook_id')
    op.add_column('message_feedback', sa.Column('user_id', sa.String(length=100), nullable=False))
    op.add_column('message_feedback', sa.Column('message_id', sa.String(length=100), nullable=False))
    op.add_column('message_feedback', sa.Column('notebook_id', sa.String(length=100), nullable=False))
    op.drop_constraint('message_feedback_fk_feedback_user_id_fkey', 'message_feedback', type_='foreignkey')
    op.drop_constraint('message_feedback_fk_feedback_message_id_fkey', 'message_feedback', type_='foreignkey')
    op.drop_constraint('message_feedback_fk_feedback_notebook_id_fkey', 'message_feedback', type_='foreignkey')
    op.create_foreign_key('fk_feedback_message_id', 'message_feedback', 'message_log', ['message_id'], ['message_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_feedback_user_id', 'message_feedback', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_feedback_notebook_id', 'message_feedback', 'notebook', ['notebook_id'], ['notebook_id'], ondelete='CASCADE')
    op.drop_column('message_feedback', 'fk_feedback_message_id')
    op.drop_column('message_feedback', 'fk_feedback_user_id')
    op.drop_column('message_feedback', 'fk_feedback_notebook_id')
    op.add_column('message_log', sa.Column('notebook_id', sa.String(length=100), nullable=False))
    op.add_column('message_log', sa.Column('bot_id', sa.String(length=100), nullable=False))
    op.drop_constraint('message_log_fk_message_notebook_id_fkey', 'message_log', type_='foreignkey')
    op.drop_constraint('message_log_fk_message_bot_id_fkey', 'message_log', type_='foreignkey')
    op.create_foreign_key('fk_message_bot_id', 'message_log', 'bot', ['bot_id'], ['bot_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_message_notebook_id', 'message_log', 'notebook', ['notebook_id'], ['notebook_id'], ondelete='CASCADE')
    op.drop_column('message_log', 'fk_message_notebook_id')
    op.drop_column('message_log', 'fk_message_bot_id')
    op.add_column('note', sa.Column('notebook_id', sa.String(length=100), nullable=False))
    # op.drop_constraint('note_fk_note_chunk_id_fkey', 'note', type_='foreignkey')
    op.drop_constraint('note_fk_note_notebook_id_fkey', 'note', type_='foreignkey')
    op.create_foreign_key('fk_note_notebook_id', 'note', 'notebook', ['notebook_id'], ['notebook_id'], ondelete='CASCADE')
    op.drop_column('note', 'fk_note_notebook_id')
    op.drop_column('note', 'fk_note_chunk_id')
    op.add_column('notebook', sa.Column('user_id', sa.String(length=100), nullable=False))
    op.drop_constraint('notebook_fk_notebook_user_id_fkey', 'notebook', type_='foreignkey')
    op.create_foreign_key('fk_notebook_user_id', 'notebook', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('notebook', 'fk_notebook_user_id')
    op.add_column('systemfeedback', sa.Column('user_id', sa.String(length=100), nullable=False))
    op.drop_constraint('systemfeedback_fk_sysfeedback_user_id_fkey', 'systemfeedback', type_='foreignkey')
    op.create_foreign_key('fk_sysfeedback_user_id', 'systemfeedback', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('systemfeedback', 'fk_sysfeedback_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('systemfeedback', sa.Column('fk_sysfeedback_user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint('fk_sysfeedback_user_id', 'systemfeedback', type_='foreignkey')
    op.create_foreign_key('systemfeedback_fk_sysfeedback_user_id_fkey', 'systemfeedback', 'user', ['fk_sysfeedback_user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('systemfeedback', 'user_id')
    op.add_column('notebook', sa.Column('fk_notebook_user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint('fk_notebook_user_id', 'notebook', type_='foreignkey')
    op.create_foreign_key('notebook_fk_notebook_user_id_fkey', 'notebook', 'user', ['fk_notebook_user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('notebook', 'user_id')
    op.add_column('note', sa.Column('fk_note_chunk_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('note', sa.Column('fk_note_notebook_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint('fk_note_notebook_id', 'note', type_='foreignkey')
    op.create_foreign_key('note_fk_note_notebook_id_fkey', 'note', 'notebook', ['fk_note_notebook_id'], ['notebook_id'], ondelete='CASCADE')
    op.create_foreign_key('note_fk_note_chunk_id_fkey', 'note', 'chunk', ['fk_note_chunk_id'], ['chunk_id'], ondelete='CASCADE')
    op.drop_column('note', 'notebook_id')
    op.add_column('message_log', sa.Column('fk_message_bot_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('message_log', sa.Column('fk_message_notebook_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint('fk_message_notebook_id', 'message_log', type_='foreignkey')
    op.drop_constraint('fk_message_bot_id', 'message_log', type_='foreignkey')
    op.create_foreign_key('message_log_fk_message_bot_id_fkey', 'message_log', 'bot', ['fk_message_bot_id'], ['bot_id'], ondelete='CASCADE')
    op.create_foreign_key('message_log_fk_message_notebook_id_fkey', 'message_log', 'notebook', ['fk_message_notebook_id'], ['notebook_id'], ondelete='CASCADE')
    op.drop_column('message_log', 'bot_id')
    op.drop_column('message_log', 'notebook_id')
    op.add_column('message_feedback', sa.Column('fk_feedback_notebook_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('message_feedback', sa.Column('fk_feedback_user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('message_feedback', sa.Column('fk_feedback_message_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint('fk_feedback_notebook_id', 'message_feedback', type_='foreignkey')
    op.drop_constraint('fk_feedback_user_id', 'message_feedback', type_='foreignkey')
    op.drop_constraint('fk_feedback_message_id', 'message_feedback', type_='foreignkey')
    op.create_foreign_key('message_feedback_fk_feedback_notebook_id_fkey', 'message_feedback', 'notebook', ['fk_feedback_notebook_id'], ['notebook_id'], ondelete='CASCADE')
    op.create_foreign_key('message_feedback_fk_feedback_message_id_fkey', 'message_feedback', 'message_log', ['fk_feedback_message_id'], ['message_id'], ondelete='CASCADE')
    op.create_foreign_key('message_feedback_fk_feedback_user_id_fkey', 'message_feedback', 'user', ['fk_feedback_user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('message_feedback', 'notebook_id')
    op.drop_column('message_feedback', 'message_id')
    op.drop_column('message_feedback', 'user_id')
    op.add_column('file', sa.Column('fk_file_notebook_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint('fk_file_notebook_id', 'file', type_='foreignkey')
    op.create_foreign_key('file_fk_file_notebook_id_fkey', 'file', 'notebook', ['fk_file_notebook_id'], ['notebook_id'], ondelete='CASCADE')
    op.drop_column('file', 'notebook_id')
    op.create_table('chunk',
    sa.Column('chunk_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fk_chunk_file_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_chunk_file_id'], ['file.file_id'], name='chunk_fk_chunk_file_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id', name='chunk_pkey')
    )
    # ### end Alembic commands ###
