"""create initial tables

Revision ID: 8d675daa3dad
Revises: 
Create Date: 2024-10-31 21:45:33.059639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d675daa3dad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot',
    sa.Column('bot_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('bot_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='user_role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('notebook',
    sa.Column('notebook_id', sa.String(length=100), nullable=False),
    sa.Column('fk_notebook_user_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fk_notebook_user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notebook_id')
    )
    op.create_table('systemfeedback',
    sa.Column('feedback_id', sa.String(length=100), nullable=False),
    sa.Column('fk_sysfeedback_user_id', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fk_sysfeedback_user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('file',
    sa.Column('file_id', sa.String(length=100), nullable=False),
    sa.Column('fk_file_notebook_id', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.Enum('pdf', 'docx', 'txt', name='file_extension_enum'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fk_file_notebook_id'], ['notebook.notebook_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('message_log',
    sa.Column('message_id', sa.String(length=100), nullable=False),
    sa.Column('fk_message_notebook_id', sa.String(length=100), nullable=False),
    sa.Column('fk_message_bot_id', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('from_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fk_message_bot_id'], ['bot.bot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fk_message_notebook_id'], ['notebook.notebook_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('chunk',
    sa.Column('chunk_id', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('fk_chunk_file_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fk_chunk_file_id'], ['file.file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_table('message_feedback',
    sa.Column('feedback_id', sa.String(length=100), nullable=False),
    sa.Column('fk_feedback_user_id', sa.String(length=100), nullable=False),
    sa.Column('fk_feedback_message_id', sa.String(length=100), nullable=False),
    sa.Column('fk_feedback_notebook_id', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fk_feedback_message_id'], ['message_log.message_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fk_feedback_notebook_id'], ['notebook.notebook_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fk_feedback_user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('note',
    sa.Column('note_id', sa.String(length=100), nullable=False),
    sa.Column('fk_note_notebook_id', sa.String(length=100), nullable=False),
    sa.Column('fk_note_chunk_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fk_note_chunk_id'], ['chunk.chunk_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fk_note_notebook_id'], ['notebook.notebook_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    op.drop_table('message_feedback')
    op.drop_table('chunk')
    op.drop_table('message_log')
    op.drop_table('file')
    op.drop_table('systemfeedback')
    op.drop_table('notebook')
    op.drop_table('user')
    op.drop_table('bot')
    # ### end Alembic commands ###
