"""Add new fields to File model

Revision ID: c24594d6b148
Revises: 709f70c74930
Create Date: 2024-11-11 15:34:33.662389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24594d6b148'
down_revision: Union[str, None] = '709f70c74930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('user_id', sa.String(length=100), nullable=False))
    op.add_column('file', sa.Column('session_id', sa.String(length=100), nullable=True))
    op.add_column('file', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('file', sa.Column('updated_by', sa.String(length=100), nullable=True))
    op.create_foreign_key('fk_file_user_id', 'file', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_file_user_id', 'file', type_='foreignkey')
    op.drop_column('file', 'updated_by')
    op.drop_column('file', 'file_size')
    op.drop_column('file', 'session_id')
    op.drop_column('file', 'user_id')
    # ### end Alembic commands ###
